### ISSUE TITLE
Maintainers for the Community repo

### ISSUE THREAD

**Issue by geekygirldawn** [coredashio/community#2]
Right now @amye, @caniszczyk, and I are the only ones who can merge PRs and perform other maintainer tasks for CoreDash. I think we should open this up to a few other people who would have write access to the community repo. We probably only need 2-3 additional people.

I'll start with a couple of recommendations based on their reviews of our first PR: @juliusv and @Nexucis. Are either of you interested in helping maintain this repo?

Anyone else interested? It might be good to have 1 more person in a more US-friendly time zone.

**Comment by Nexucis** [comment]
For the moment yeah it's fine for me @geekygirldawn :)

**Comment by juliusv** [comment]
Same here. Not sure how much I will be able to get involved in this on a day-to-day basis, but we'll see :)

**Comment by geekygirldawn** [comment]
PR to add both of you as maintainers has been merged.
